/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx,html,css}"],
  theme: {
    extend: {
      colors: {
        primary: "var(--theme-primary)",
        onPrimary: "var(--theme-on-primary)",
        secondary: "var(--theme-secondary)",
        onSecondary: "var(--theme-on-secondary)",
        error: "var(--theme-error)",
        onError: "var(--theme-on-error)",
        success: "var(--theme-success)",
        onSuccess: "var(--theme-on-success)",
        borderColor: "var(--theme-border-color)",
        accent: "var(--theme-accent)",
        disabledColor: "var(--theme-disabled)",
        onDisabled: "var(--theme-on-disabled)",
      },
      fontFamily: {
        "sans-serif": [
          "Roboto",
          "Lato",
          "Sora",
          "Poppins",
          "Raleway",
          "Oswald",
          "Montserrat Alternates",
          "Anton",
          "Archivo",
          "Encode Sans",
          "Epilogue",
          "Work Sans",
        ],
        TiroBangla: "Tiro Bangla",
        serif: [
          "Lora",
          "Andada Pro",
          "Hahmlet",
          "Cormorant",
          "Old Standard TT",
          "Playfair Display",
          "Anton",
          "Archivo",
        ],
        monospace: ["JetBrains Mono", "Source Code Pro"],
        "bangla-uni": ["Noto Serif Bengali", "Baloo Da 2"],
        galada: ["Galada"],
        "mrs-saint-delafield": ["Mrs Saint Delafield"],
        amita: ["Amita"],
        cookie: ["Cookie"],
        "rock-salt": ["Rock Salt"],
        sacramento: ["Sacramento"],
        hurricane: ["Hurricane"],
        stalemate: ["Stalemate"],
        "ms-madi": ["Ms Madi"],
        kolker: ["Kolker Brush"],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/typography")],
};
